name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Dependencies and Build
        run: |
          npm install --force
          npm run build

      - name: Deploy to Firebase Hosting
        run: |
          export FIREBASE_TOKEN=$(npx firebase-tools login:ci --json | jq -r .token)
          echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > service-account-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/service-account-key.json
          npx firebase-tools deploy --only hosting --project todoapp-401521 --token "$FIREBASE_TOKEN" --debug
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}


